### ISSUE TITLE
Strugling to use this on a Linux server

### ISSUE THREAD

**Issue by ZhangWei-bi** [iansampson/AppAttest#4]
Hello, thanks for this lib. This is not really and issue but more to have an open conversation. Do you have any suggestion on how to use this code on a Linux server? I know it's possible to use Swift in Linux, but it's a bit complicated and adds extra layers. https://www.kodeco.com/8325890-a-complete-guide-to-swift-development-on-linux 

It would have been awesome if the verification code was written in C++. Still I'm grateful for the work you did. Was the intention of the lib to host a server on MacOS? Maybe I should somehow host an http server with this Swift code with this? https://github.com/httpswift/swifter

I was looking at https://www.darlinghq.org/ so I could run the osx app in Linux.

**Comment by iansampson** [comment]
Hi, thanks for your interest! Happy to help if I can.

This package is indeed intended to run on a Linux server (or alternately a serverless function). No need for macOS. That said, it only really makes sense to use this repo if you’re writing your backend in Swift (which many iOS developers do), since you’d need to add this package as a dependency and call the API from your own Swift code.

If you do decide to go that route, the Kodeco tutorial you linked has a good explanation of how to install Swift on Linux. You can download the appropriate snapshot for your version of Linux at [https://www.swift.org/download](url). Once you download it (with `curl`, for example), you just need to decompress the .tar archive and export the binary path to your shell. If you have any trouble with installation, the folks over on the [Swift Forums](https://forums.swift.org) are always super helpful.

**Comment by ZhangWei-bi** [comment]
Great, I was able to use this library in Linux and I made a server with Kitura. Works perfect, thanks!

**Comment by iansampson** [comment]
No problem, glad you got it working!
